#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright 2025 David Guillen Fandos <david@davidgf.net>

# Dumps patches generated by the web-based patch tool

import sys, struct

p = open(sys.argv[1], "rb").read()

SAVETS = ["No save", "SRAM (32KiB)", "EEPROM (512b)", "EEPROM (8KiB)", "FLASH (64KiB)", "FLASH (128KiB)"]

if p[:13] != b"SUPERFWPATCHV":
  print("Invalid header magic!")
else:
  ver = p[13:15]
  print("Patch version: %s" % ver.decode("ascii"))

  wcnt, sav, savtype, irqp, rtcp, hinfo = struct.unpack("<BBBBBxIxxxxxx", p[16:32])

  print("Save Type: %d [%s]" % (savtype, SAVETS[savtype]))

  print("WaitCNT patches (%d entries)" % wcnt)
  pdata = p[32+256:]
  i = 0
  while i < wcnt+sav+irqp+rtcp:
    if i == wcnt:
      print("Save patches (%d entries):" % sav)
    if i == wcnt+sav:
      print("IRQh patches (%d entries):" % irqp)
    if i == wcnt+sav+irqp:
      print("RTC patches (%d entries):" % rtcp)

    w32 = struct.unpack("<I", pdata[i*4:i*4+4])[0]
    opc = w32 >> 28
    arg = (w32 >> 25) & 7
    moff = (w32 & 0x1FFFFFF)

    if opc == 0:
      print("  Write program %d to address %08x" % (arg, moff))
    elif opc == 1:
      print("  Thumb nop to address %08x" % moff)
    elif opc == 2:
      print("  ARM to address %08x" % moff)
    elif opc == 3:
      print("  Write %d bytes to address %08x" % (arg+1, moff))
      i += (arg + 1 + 4) // 4
    elif opc == 4:
      print("  Write %d words to address %08x" % (arg+1, moff))
      i += (arg + 1)
    elif opc == 5:
      print("  Write dummy func #%d" % arg)
    elif opc == 7:
      print("  RTC handler #%d" % arg)
    elif opc == 8:
      print("  EEPROM handler #%d" % arg)
    elif opc == 9:
      print("  FLASH handler #%d at %08x" % (arg, moff))

    i += 1

  if hinfo:
    print("Hole/Layout at: %08x of size %d KiB" % ((hinfo >> 16) << 10, hinfo & 0xffff))


