name: Patches release build
run-name: Build patches release in several formats

on:
  push:
    branches: ["master"]

jobs:
  build-patches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare build
        run: mkdir build
      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: Build DB
        run: ./tools/patch_gen.py --input patches/autogen/patches-merged-*.json --outfile build/patches.db --format db --version "${{ steps.slug.outputs.sha8 }}" --creator "github-davidgfnet-automation"
      - name: Build JSON dump
        run: ./tools/patch_gen.py --input patches/autogen/patches-merged-*.json --outfile build/patches.json --format json --version "${{ steps.slug.outputs.sha8 }}" --creator "github-davidgfnet-automation"
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: gba-patches-${{ steps.slug.outputs.sha8 }}
          path: build/*

